apiVersion: v1
kind: Namespace
metadata:
    name: $org

---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: $pvName
# spec:
#   capacity:
#     storage: 500Mi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     path: $path
#     server: 10.112.122.9  #change to your nfs server ip here

kind: PersistentVolume
apiVersion: v1
metadata:
  name: $pvName
  labels:
    type: local
    org:  $org
    label:  $pvName
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/share"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvName
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     type: local
     org: $org
     label: $pvName

---
